### ISSUE TITLE
Not show me a hosts

### ISSUE THREAD

**Issue by hvalchanov** [stdonato/zabgraphs#4]
Hi can you help me a little.
I setup the zabgraphs and work for me but not show me a hosts from zabbix.
Show me only Zabbix Server graphs on first page.
![zabgraphs](https://user-images.githubusercontent.com/51789678/59436339-17ab0300-8df8-11e9-9c32-68c3086ea30f.png)

<?php

require_once 'inc/functions.inc.php';

$zabServer = "192.168.10.63";
$zabUser = "";
$zabPass = "";
$zabURL = "http://192.168.10.63/";

//Translate option: en_US or pt_BR
$useridlang = get_userid(CWebUser::getSessionCookie());
$lang = get_user_lang($useridlang);
$labels = include_once 'locales/'.$lang.'.php';

$version = '0.0.5';

?>

**Comment by stdonato** [comment]
Hi, what's your zabbix version and zabbix server O.S.?

**Comment by hvalchanov** [comment]
Hi 10x for the fast answer.
My zabbix server is Zabbix 3.4.15. © 2001–2018 and the OS is Ubuntu jessie/sid.

**Comment by stdonato** [comment]
Please get this file: https://github.com/stdonato/zabgraphs/blob/master/zabgraphs_3.php
Copy to your server zabgraphs folder and rename to zabgraphs.php

Let me know if  it's works.

**Comment by hvalchanov** [comment]
Hello thank you so much for your assistance.
Now in left menu i see the hosts. But when I click to host nothing has change in other frame. Just show me Zabbix Server graphs.
The Search work too.
![zabbixscreen](https://user-images.githubusercontent.com/51789678/59490896-7753ed80-8e8e-11e9-8618-fbcb063f67d3.png)

**Comment by stdonato** [comment]
Hi,
Select the host or host group at left menu, select the time period, or left
the default, and click at Send button.
On the item field you can choose items like CPU, memory, traffic, etc.

Regards,

Stevenes Donato

Em sex, 14 de jun de 2019 03:23, hvalchanov <notifications@github.com>
escreveu:

**Comment by SergZezulkin** [comment]
Have the same issue on Ubuntu 14.04.5 LTS Zabbix 4.2.0
Can you help me?

**Comment by myhellone** [comment]
![obraz](https://user-images.githubusercontent.com/21089637/61234353-222c2580-a733-11e9-8f3f-f5d18ae66fc6.png)
Hi 
After install.... 
zabbix 4.2.3
zabbix server os  gentoo 
Can you help me?

**Comment by hvalchanov** [comment]
> 
> 
> Hi, what's your zabbix version and zabbix server O.S.?

Hi Works Perfect Tnaks fo asking
