### ISSUE TITLE
Zabgraphs trying to load all the graphs from hosts

### ISSUE THREAD

**Issue by Isonone** [stdonato/zabgraphs#6]
Hi,

Unfortunately this is not usable using large infrastructure with thousands of graphs. On login to zabgraphs I can see from apache log, it is trying to load all the graphs for all hosts. We have 10k+ hosts and this is just causing browser crash. The original grphtree has the possibility to load the graphs on request, or when expanding the tree. Are you consider to re-write the code adding this functionality? Thanks

**Comment by mk-git** [comment]
We have the same problem. Is there any news?
With us the list loads (which really VERY much time needed).
Then I can not search for hosts and see nothing on the left side of the list.

**Comment by stdonato** [comment]
Hi, by default zabgraphs search for a host named "Zabbix server", if you don't have such host, so loads all host. I changed the code to search for the ID of the first host, the lowest host ID in zabbix.
If you want test, get the new zabgraphs.php file and copy to your zabbix server.

**Comment by mk-git** [comment]
Hi. Thank you for the hint. Unfortunately, it has not worked 100% yet. I still had to adjust the line and replace the quotes with comma. See working example:

`$ dbZabServer = DBselect ("SELECT hostid FROM hosts WHERE name NOT LIKE '% Templa%' ORDER by hostid ASC LIMIT 1");`

Then it works and after the login is super fast. BUT, the search links above and the tree view is also not visible. Do you have a hint here?

**Comment by stdonato** [comment]
What is the operating system of your server and your PHP version?

**Comment by mk-git** [comment]
Debian 9.11, PHP Version 7.0.33-0+deb9u5
