### ISSUE TITLE
No data and graph in Zabbix 4.4

### ISSUE THREAD

**Issue by Kencow** [stdonato/zabgraphs#9]
Hello, I install zabgraphs in Zabbix 4.4, hosts' tree can be displayed but no graph appears, any help ?  

zabbix 4.4 @ Ubuntu 18.04.4

![image](https://user-images.githubusercontent.com/15882453/81246133-61708d80-9049-11ea-9db6-86566e7cca04.png)

**Comment by stdonato** [comment]
Zabbix 4.4.8

![Firefox_Screenshot_2020-05-07T13-19-03 376Z](https://user-images.githubusercontent.com/7674445/81299731-a7772280-9044-11ea-8443-b7a209338504.png)

**Comment by Kencow** [comment]
Hi @stdonato , my problem is fixed because I give a wrong zabbix user in config.php. 
The graphs are showed now but it lacks the period menu on top-right, any suggestion?

![image](https://user-images.githubusercontent.com/15882453/81367034-b5997180-911e-11ea-96b2-9b2afced60a3.png)
